project:
  type: website

website:
  title: "Adam Cseresznye"
  page-footer: "Copyright 2024, Adam Cseresznye" 
  google-analytics: "UA-BQF3JENT9N"
  favicon: favicon_lower_A.png
  open-graph: true
  twitter-card: true
  reader-mode: true
  navbar:
    left: 
      - scientific_output.qmd
    right:
      - articles.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/adamcseresznye
      - icon: twitter
        href: https://twitter.com/csenye22
      - icon: linkedin
        href: https://www.linkedin.com/in/adam-cseresznye

format:
  html:
    css: styles.css
    theme: 
       light: [litera, styles.scss]
       dark: [darkly, styles-dark.scss]



